## Product API

### 이리내 추가 요청

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "이리내",
  "price": 10000000,
  "imageUrl": "#"
}

### 전체 상품 조회 요청

GET http://localhost:8080/products
Content-Type: application/json

### 특정 상품 조회 요청

GET http://localhost:8080/products/1
Content-Type: application/json

### 깃짱 수정 요청 (가격 수정)

PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "name": "깃짱코딩",
  "price": 150000,
  "imageUrl": "#"
}

### 제리 삭제 요청

DELETE http://localhost:8080/products/2
Content-Type: application/json

## Member API

### 전체 멤버 조회

GET http://localhost:8080/members
Content-Type: application/json

### 특정 멤버 조회

GET http://localhost:8080/members/1
Content-Type: application/json

## Cart Item API

### 장바구니 아이템 목록 조회

GET http://localhost:8080/cart-items
Authorization: Basic ${credentials}

### 장바구니 아이템 추가

POST http://localhost:8080/cart-items
Authorization: Basic ${credentials}
Content-Type: application/json

{
  "productId": 1
}

### 장바구니 아이템 수량 변경

PATCH http://localhost:8080/cart-items/1
Authorization: Basic ${credentials}
Content-Type: application/json

{
  "quantity": 3
}

### 장바구니 아이템 삭제

DELETE http://localhost:8080/cart-items/1
Authorization: Basic ${credentials}성
