SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE product;
TRUNCATE TABLE member;
TRUNCATE TABLE cart_item;
TRUNCATE TABLE order_history;
TRUNCATE TABLE order_product;
TRUNCATE TABLE point;
SET REFERENTIAL_INTEGRITY TRUE;