### 주문 생성(쿠폰 O)
POST http://localhost:8080/orders
Authorization: Basic YUBhLmNvbToxMjM0
Content-Type: application/json

{
  "cartItemIdList" : [1,2,3],
  "totalPrice" : 585400,
  "deliveryFee" : 3000,
  "couponId" : 1
}

### 주문 생성(쿠폰 X)
POST http://localhost:8080/orders
Authorization: Basic YUBhLmNvbToxMjM0
Content-Type: application/json

{
  "cartItemIdList" : [6],
  "totalPrice" : 82000,
  "deliveryFee" : 3000
}

### 사용자의 모든 주문 조회
GET http://localhost:8080/orders
Authorization: Basic YUBhLmNvbToxMjM0

### 주문 상세 조회
GET http://localhost:8080/orders/3
Authorization: Basic YUBhLmNvbToxMjM0

### 주문 삭제
DELETE http://localhost:8080/orders/4
Authorization: Basic YUBhLmNvbToxMjM0

### 주문 상태 변경
PATCH http://localhost:8080/orders/4
Authorization: Basic YUBhLmNvbToxMjM0

