### 쿠폰할인 적용
GET http://localhost:8080/coupons/discount?total-price=10000&member-coupon-id=1
Accept: application/json

### response
HTTP/1.1 200
Content-Type: application/json

{
  "discountPrice": -5000,
  "totalPrice": 5000
}

### 멤버의 쿠폰 전체 조회하기
GET http://localhost:8080/coupons
Accept: application/json
Authorization: Basic c2FuZ3VuOjEyMzQ=

### response
HTTP/1.1 200
Content-Type: application/json

[
  {
    "memberCouponId": 1,
    "name": "50% 할인쿠폰"
  },
  {
    "memberCouponId": 2,
    "name": "5000원 할인쿠폰"
  }
]

### 멤버의 쿠폰 발급받기(테스트 용)
POST http://localhost:8080/coupons/1/issue
Authorization: Basic c2FuZ3VuOjEyMzQ=

### response
HTTP/1.1 201
