### 상품 주문
POST {{baseUrl}}/orders
Authorization: Basic {{credentials}}
Content-Type: application/json

{
  "items": [
    {
      "productId": 1,
      "quantity": 5
    },
    {
      "productId": 2,
      "quantity": 100
    }
  ],
  "couponId": 1
}

### 주문 내역 조회
GET {{baseUrl}}/orders
Authorization: Basic {{credentials}}
Content-Type: application/json

### 주문 상품 상세 조회
GET {{baseUrl}}/orders/1
Authorization: Basic {{credentials}}
Content-Type: application/json
