# 1번째 계정 : Basic YUBhLmNvbToxMjM0
# 2번째 계정 : Basic YkBiLmNvbToxMjM0

###
# @name createProduct
# @description Creates a new product
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "햄버거",
  "price": 6000,
  "imageUrl": "aa",
  "pointRatio": 31.6,
  "pointAvailable": true
}

> Expected response:
> Status: 201 Created
> Headers: Location: http://localhost:8080/products/{productId}


###
# @name getProductById
# @description Retrieves a specific product by its ID
GET http://localhost:8080/products/4
Content-Type: application/json

> Expected response:
> Status: 200 OK
> Body:
> {
>   "id": 4,
>   "name": "햄버거",
>   "price": 6000,
>   "imageUrl": "aa",
>   "pointRatio": 31.6,
>   "pointAvailable": true
> }


###
# @name getAllProducts
# @description Retrieves all products
GET http://localhost:8080/products
Content-Type: application/json

> Expected response:
> Status: 200 OK
> Body:
> [
>   {
>     "id": 1,
>     "name": "치킨",
>     "price": 10000,
>     "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>     "pointRatio": 10.0,
>     "pointAvailable": true
>   },
>   {
>     "id": 2,
>     "name": "샐러드",
>     "price": 20000,
>     "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>     "pointRatio": 10.0,
>     "pointAvailable": false
>   },
>   {
>     "id": 3,
>     "name": "피자",
>     "price": 13000,
>     "imageUrl": "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
>     "pointRatio": 10.0,
>     "pointAvailable": true
>   },
>   {
>     "id": 4,
>     "name": "햄버거",
>     "price": 6000,
>     "imageUrl": "aa",
>     "pointRatio": 31.6,
>     "pointAvailable": true
>   }
> ]


###
# @name getCurrentPoint
# @description Retrieves the current points for a specific member
GET http://localhost:8080/point
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0

> Expected response:
> Status: 200 Ok
> {
>   "point": 30000
> }


###
# @name showCartItems
# @description Retrieves a list of cart items for a specific member
GET http://localhost:8080/cart-items
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0 # 1번째 계정

> Expected response:
> Status: 200 OK
> Body:
> [
>   {
>     "id": 1,
>     "quantity": 2,
>     "product": {
>       "id": 1,
>       "name": "치킨",
>       "price": 10000,
>       "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": true
>     }
>   },
>   {
>     "id": 2,
>     "quantity": 4,
>     "product": {
>       "id": 2,
>       "name": "샐러드",
>       "price": 20000,
>       "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": false
>     }
>   },
>   {
>     "id": 4,
>     "quantity": 5,
>     "product": {
>       "id": 3,
>       "name": "피자",
>       "price": 13000,
>       "imageUrl": "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": true
>     }
>   }
> ]


###
# @name addCartItems
# @description Adds an item to a member's cart
POST http://localhost:8080/cart-items
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0 # 1번째 계정

{
  "productId": 4
}

> Expected response:
> Status: 201 Created
> Headers: Location: http://localhost:8080/cart-items/{cartItemId}


###
# @name showCartItems
# @description Retrieves a list of cart items for a specific member
GET http://localhost:8080/cart-items
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0 # 1번째 계정

> Expected response:
> Status: 200 OK
> Body:
> [
>   {
>     "id": 1,
>     "quantity": 2,
>     "product": {
>       "id": 1,
>       "name": "치킨",
>       "price": 10000,
>       "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": true
>     }
>   },
>   {
>     "id": 2,
>     "quantity": 4,
>     "product": {
>       "id": 2,
>       "name": "샐러드",
>       "price": 20000,
>       "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": false
>     }
>   },
>   {
>     "id": 4,
>     "quantity": 5,
>     "product": {
>       "id": 3,
>       "name": "피자",
>       "price": 13000,
>       "imageUrl": "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": true
>     }
>   },
>   {
>     "id": 5,
>     "quantity": 1,
>     "product": {
>       "id": 4,
>       "name": "햄버거",
>       "price": 6000,
>       "imageUrl": "aa",
>       "pointRatio": 31.6,
>       "pointAvailable": true
>     }
>   }
> ]


###
# @name updateCartItemQuantity
# @description Updates the quantity of a cart item for a member
PATCH http://localhost:8080/cart-items/1
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0 # 1번째 계정

{
  "quantity": 120
}

> Expected response:
> Status: 200 Ok


###
# @name showCartItems
# @description Retrieves a list of cart items for a specific member
GET http://localhost:8080/cart-items
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0 # 1번째 계정

> Expected response:
> Status: 200 OK
> Body:
> [
>   {
>     "id": 1,
>     "quantity": 120,
>     "product": {
>       "id": 1,
>       "name": "치킨",
>       "price": 10000,
>       "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": true
>     }
>   },
>   {
>     "id": 2,
>     "quantity": 4,
>     "product": {
>       "id": 2,
>       "name": "샐러드",
>       "price": 20000,
>       "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": false
>     }
>   },
>   {
>     "id": 4,
>     "quantity": 5,
>     "product": {
>       "id": 3,
>       "name": "피자",
>       "price": 13000,
>       "imageUrl": "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": true
>     }
>   },
>   {
>     "id": 5,
>     "quantity": 1,
>     "product": {
>       "id": 4,
>       "name": "햄버거",
>       "price": 6000,
>       "imageUrl": "aa",
>       "pointRatio": 31.6,
>       "pointAvailable": true
>     }
>   }
> ]


###
# @name removeCartItems
# @description Removes an item from a member's cart
DELETE http://localhost:8080/cart-items/4
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0

> Expected response:
> Status: 204 No Content


###
# @name showCartItems
# @description Retrieves a list of cart items for a specific member
GET http://localhost:8080/cart-items
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0 # 1번째 계정

> Expected response:
> Status: 200 OK
> Body:
> [
>   {
>     "id": 1,
>     "quantity": 120,
>     "product": {
>       "id": 1,
>       "name": "치킨",
>       "price": 10000,
>       "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": true
>     }
>   },
>   {
>     "id": 2,
>     "quantity": 4,
>     "product": {
>       "id": 2,
>       "name": "샐러드",
>       "price": 20000,
>       "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>       "pointRatio": 10.0,
>       "pointAvailable": false
>     }
>   },
>   {
>     "id": 5,
>     "quantity": 1,
>     "product": {
>       "id": 4,
>       "name": "햄버거",
>       "price": 6000,
>       "imageUrl": "aa",
>       "pointRatio": 31.6,
>       "pointAvailable": true
>     }
>   }
> ]


###
# @name updateCartItemQuantity
# @description Updates the quantity of a cart item for a member
PATCH http://localhost:8080/cart-items/1
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0 # 1번째 계정

{
  "quantity": 10
}

> Expected response:
> Status: 200 Ok


###
# @name order
# @description Creates a new order for a member
POST http://localhost:8080/orders
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0

{
  "cartItems": [
    {
      "cartItemId": 1
    },
    {
      "cartItemId": 2
    },
    {
      "cartItemId": 5
    }
  ],
  "originalPrice": 186000,
  "usedPoint": 5000,
  "pointToAdd": 19896
}

> Expected response:
> Status: 201 Created


###
# @name showCartItems
# @description Retrieves a list of cart items for a specific member
GET http://localhost:8080/cart-items
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0 # 1번째 계정

> Expected response:
> Status: 200 OK
> Body:
> []


###
# @name getOrders
# @description Retrieves a list of orders for a specific member
GET http://localhost:8080/orders
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0

> Expected response:
> Status: 200 Ok
> Body:
> [
>   {
>     "orderId": 1,
>     "orderInfo": [
>       {
>         "productId": 4,
>         "price": 6000,
>         "name": "햄버거",
>         "imageUrl": "aa",
>         "quantity": 1
>       },
>       {
>         "productId": 2,
>         "price": 20000,
>         "name": "샐러드",
>         "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>         "quantity": 4
>       },
>       {
>         "productId": 1,
>         "price": 10000,
>         "name": "치킨",
>         "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>         "quantity": 10
>       }
>     ]
>   }
> ]


###
# @name getOrder
# @description Retrieves a specific order by its ID for a specific member
GET http://localhost:8080/orders/1
Content-Type: application/json
Authorization: Basic YUBhLmNvbToxMjM0

> Expected response:
> Status: 200 Ok
> Body:
> {
>   "orderId": 1,
>   "orderInfo": [
>     {
>       "productId": 4,
>       "price": 6000,
>       "name": "햄버거",
>       "imageUrl": "aa",
>       "quantity": 1
>     },
>     {
>       "productId": 2,
>       "price": 20000,
>       "name": "샐러드",
>       "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>       "quantity": 4
>     },
>     {
>       "productId": 1,
>       "price": 10000,
>       "name": "치킨",
>       "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80",
>       "quantity": 10
>     }
>   ],
>   "originalPrice": 186000,
>   "usedPoint": 5000,
>   "pointToAdd": 19896
> }
