= 장바구니 API Docs
도담 클린 최고
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:

[[Product-API]]
== Product API

[[상품-목록-조회-API]]
=== 상품 목록 조회
operation::get-products[snippets='http-request,http-response,response-fields']

[[상품-조회-API]]
=== 상품 조회
operation::get-product[snippets='http-request,path-parameters,http-response,response-fields']

[[상품-추가-API]]
=== 상품 추가
operation::create-product[snippets='http-request,request-fields,http-response']

[[상품-수정-API]]
=== 상품 수정
operation::update-product[snippets='http-request,path-parameters,request-fields,http-response']

[[상품-삭제-API]]
=== 상품 삭제
operation::delete-product[snippets='http-request,path-parameters,http-response']

[[장바구니-상품-API]]
== Cart Item API

[[장바구니-상품-추가-API]]
=== 장바구니 상품 추가
operation::add-cart-item[snippets='http-request,request-fields,http-response']

[[장바구니-상품-삭제-API]]
=== 장바구니 상품 삭제 API
operation::delete-cart-item[snippets='http-request,path-parameters,http-response']

[[장바구니-상품-수량-수정-API]]
=== 장바구니 상품 수량 수정 API
operation::update-cart-item-quantity[snippets='http-request,http-response']
