package cart.exception;

public enum ExceptionType {
    LOGIN_FAIL,
    FORBIDDEN, PRODUCT_NO_EXIST, INVALID_FORM, ORDER_NO_EXIST, CART_ITEM_EMPTY, CART_ITEM_NO_EXIST, COUPON_UNVAILABLE, COUPON_NO_EXIST, UNAUTHORIZED
}
