### 주문내역 상세 조회
GET http://localhost:8080/orders/1
Accept: application/json
Authorization: basic YUBhLmNvbToxMjM0

### response
HTTP/1.1 200
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Jun 2023 14:52:03 GMT
Keep-Alive: timeout=60
Connection: keep-alive

{
  "id": 1,
  "orderProducts": [
    {
      "productResponseDto": {
        "id": 1,
        "name": "치킨",
        "price": 10000,
        "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
      },
      "quantity": 2
    },
    {
      "productResponseDto": {
        "id": 2,
        "name": "샐러드",
        "price": 20000,
        "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
      },
      "quantity": 2
    },
    {
      "productResponseDto": {
        "id": 3,
        "name": "피자",
        "price": 13000,
        "imageUrl": "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80"
      },
      "quantity": 2
    }
  ],
  "timestamp": "2023-01-01T12:00",
  "originPrice": 86000,
  "discountPrice": 5000,
  "totalPrice": 81000
}

### 전체 주문내역 조회하기
GET http://localhost:8080/orders
Accept: application/json
Authorization: basic YUBhLmNvbToxMjM0

### response
HTTP/1.1 200
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Jun 2023 14:52:33 GMT
Keep-Alive: timeout=60
Connection: keep-alive

[
  {
    "id": 1,
    "orderProducts": [
      {
        "productResponseDto": {
          "id": 1,
          "name": "치킨",
          "price": 10000,
          "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
        },
        "quantity": 2
      },
      {
        "productResponseDto": {
          "id": 2,
          "name": "샐러드",
          "price": 20000,
          "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
        },
        "quantity": 2
      },
      {
        "productResponseDto": {
          "id": 3,
          "name": "피자",
          "price": 13000,
          "imageUrl": "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80"
        },
        "quantity": 2
      }
    ],
    "timestamp": "2023-01-01T12:00",
    "originPrice": 86000,
    "discountPrice": 5000,
    "totalPrice": 81000
  },
  {
    "id": 2,
    "orderProducts": [
      {
        "productResponseDto": {
          "id": 1,
          "name": "치킨",
          "price": 10000,
          "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
        },
        "quantity": 2
      }
    ],
    "timestamp": "2023-01-01T12:00",
    "originPrice": 20000,
    "discountPrice": 2000,
    "totalPrice": 18000
  }
]

### 주문하기 - 쿠폰적용 하는 경우
POST http://localhost:8080/orders
Accept: application/json
Content-Type: application/json
Authorization: basic YUBhLmNvbToxMjM0

{
  "cartItemIds": [
    1,
    2
  ],
  "couponId": 1
}

### response
HTTP/1.1 201
Location: /orders/5
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Jun 2023 14:53:02 GMT
Keep-Alive: timeout=60
Connection: keep-alive

{
  "id": 5,
  "orderProducts": [
    {
      "productResponseDto": {
        "id": 1,
        "name": "치킨",
        "price": 10000,
        "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
      },
      "quantity": 2
    },
    {
      "productResponseDto": {
        "id": 2,
        "name": "샐러드",
        "price": 20000,
        "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
      },
      "quantity": 4
    }
  ],
  "timestamp": "2023-06-04T23:53:02.166210",
  "originPrice": 100000,
  "discountPrice": 5000,
  "totalPrice": 95000
}

### 주문하기 - 쿠폰적용 하지 않는 경우
POST http://localhost:8080/orders
Accept: application/json
Content-Type: application/json
Authorization: basic YUBhLmNvbToxMjM0

{
  "cartItemIds": [
    1,
    2
  ]
}

### response
HTTP/1.1 201
Location: /orders/5
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 04 Jun 2023 14:56:27 GMT
Keep-Alive: timeout=60
Connection: keep-alive

{
  "id": 5,
  "orderProducts": [
    {
      "productResponseDto": {
        "id": 1,
        "name": "치킨",
        "price": 10000,
        "imageUrl": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
      },
      "quantity": 2
    },
    {
      "productResponseDto": {
        "id": 2,
        "name": "샐러드",
        "price": 20000,
        "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2370&q=80"
      },
      "quantity": 4
    }
  ],
  "timestamp": "2023-06-04T23:56:27.363398",
  "originPrice": 100000,
  "discountPrice": 0,
  "totalPrice": 100000
}
