SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE PRODUCT;
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품1', 1000, 'www.example1.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품2', 2000, 'www.example2.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품3', 3000, 'www.example3.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품4', 4000, 'www.example4.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품5', 5000, 'www.example5.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품6', 6000, 'www.example6.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품7', 7000, 'www.example7.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품8', 8000, 'www.example8.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품9', 9000, 'www.example9.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품10', 10000, 'www.example10.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품11', 11000, 'www.example11.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품12', 12000, 'www.example12.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품13', 13000, 'www.example13.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품14', 14000, 'www.example14.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품15', 15000, 'www.example15.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품16', 16000, 'www.example16.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품17', 17000, 'www.example17.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품18', 18000, 'www.example18.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품19', 19000, 'www.example19.com');
INSERT INTO PRODUCT(name, price, image_url) VALUES('상품20', 20000, 'www.example20.com');
SET FOREIGN_KEY_CHECKS = 1;
