SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE product;
TRUNCATE TABLE member;
TRUNCATE TABLE cart_item;
TRUNCATE TABLE orders;
TRUNCATE TABLE order_item;
TRUNCATE TABLE coupon;
SET REFERENTIAL_INTEGRITY TRUE;
