DELETE FROM order_item;
DELETE FROM cart_order;
DELETE FROM cart_item;
DELETE FROM product;
DELETE FROM member;

ALTER TABLE order_item ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE cart_order ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE cart_item ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE product ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE member ALTER COLUMN ID RESTART WITH 1;
