### 상품 추가
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "진로",
  "price": 3000,
  "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaeix3NqM6r5a9o8wubIWTdgrjp1V613rO2MXIxuCyQw&s",
  "stock": 30
}

### 상품 수정
PUT http://localhost:8080/products/4
Content-Type: application/json

{
  "name": "진로",
  "price": 5000,
  "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaeix3NqM6r5a9o8wubIWTdgrjp1V613rO2MXIxuCyQw&s",
  "stock": 10
}

### 상품 삭제
DELETE http://localhost:8080/products/4

### 상품 조회
GET http://localhost:8080/products/3

### 상품 목록 조회
GET http://localhost:8080/products/

